In [76]:
# Importing Tensorflow
import tensorflow as tf

print(tf.__version__)

2.15.0


In [77]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [78]:
datasets = pd.read_csv('Churn_Modelling.csv')
datasets.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [82]:
## Divide the datasets into the independent and dependent variable.
X = datasets.iloc[:, 3:13]
Y = datasets.iloc[:, 13]

In [83]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [84]:
Y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [85]:
## Converting the categorical data into numerical data
geography = pd.get_dummies(X['Geography'], drop_first = True)
gender = pd.get_dummies(X['Gender'], drop_first = True)

In [86]:
# Concatenate these variables with dataframe
X = X.drop(['Geography', 'Gender'], axis = 1)

In [87]:
X = pd.concat([X, geography, gender], axis = 1)
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0               1        101348.88    False  False  False  
1               1        112542.58    False   True  False  
2               0        113931.57    False  False  False  
3               0         93826.63    False  False  False  
4               1         79084.10    False   True  False

In [88]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [102]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 
X_train = np.array(X_train)
Y_train = np.array(Y_train)

In [104]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [105]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [106]:
X_train.shape

(8000, 11)

In [107]:
## Now let's create ANN 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU, PReLU, ELU, ReLU
from tensorflow.keras.layers import Dropout

In [108]:
# Lets initialized ANN
classifier = Sequential()

In [123]:
# Adding input layers
classifier.add(Dense(units=11, activation='relu'))

In [124]:
# Adding the first hidden layer
classifier.add(Dense(units=7, activation='relu'))
classifier.add(Dropout(0.2))

In [125]:
# Adding the second hidden layer
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dropout(0.3))

In [126]:
# Adding the output layer
classifier.add(Dense(units=1, activation='sigmoid'))

In [127]:
# Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [128]:
# Providing our own learning rate
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01) # By default learning_rate = 0.01 

In [129]:
# Early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor = 'val_loss', mode = 'auto', verbose = 1, patience = 20, min_delta = 0.0001, baseline = 0, restore_best_weights=False)

In [130]:
# Fitting the ANN to the training set
classifier.fit(X_train, Y_train, batch_size = 10, epochs = 1000, validation_split = 0.33, callbacks=early_stop)

Epoch 1/1000
536/536 [==============================] - 2s 2ms/step - loss: 0.5080 - accuracy: 0.8149 - val_loss: 0.4051 - val_accuracy: 0.8152
Epoch 2/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3973 - accuracy: 0.8474 - val_loss: 0.3993 - val_accuracy: 0.8251
Epoch 3/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3802 - accuracy: 0.8537 - val_loss: 0.3900 - val_accuracy: 0.8459
Epoch 4/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3705 - accuracy: 0.8554 - val_loss: 0.3873 - val_accuracy: 0.8425
Epoch 5/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3711 - accuracy: 0.8531 - val_loss: 0.3862 - val_accuracy: 0.8421
Epoch 6/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3572 - accuracy: 0.8548 - val_loss: 0.3936 - val_accuracy: 0.8413
Epoch 7/1000
536/536 [==============================] - 1s 2ms/step - loss: 0.3617 - accuracy: 0.8520 - val_loss: 0.3914 - val_accuracy:

In [131]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred >= 0.5)

63/63 [==============================] - 0s 1ms/step


In [132]:
# Making confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1536,   59],
       [ 240,  165]], dtype=int64)

In [134]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, Y_test)
score

0.8505

In [135]:
# Getting the weights
classifier.get_weights()

[array([[ 0.10441624,  1.1365103 , -0.80155456,  0.36834544, -0.6084223 ,
         -0.04932959,  0.09644695, -0.63222694,  0.36980814, -0.58210593,
          1.0298632 ],
        [-0.30266544, -1.715958  , -0.19008985, -0.5364235 , -1.6861602 ,
         -1.3536899 ,  0.797786  , -0.34660894,  1.3618097 ,  1.1780895 ,
         -0.88189036],
        [-0.2225604 , -0.7828804 ,  0.88693714,  0.19909033,  0.60144025,
         -0.01854727,  0.79848796, -0.98707455,  0.30278027, -0.04774024,
         -0.25907937],
        [-0.17278744, -0.74263006, -1.2128192 ,  0.7126535 , -0.93534875,
          0.05024121,  0.7022646 ,  0.5545545 , -0.9678661 , -0.86973745,
         -1.8347665 ],
        [-2.3821323 , -0.8908632 ,  0.22851744,  2.3735993 ,  0.4571287 ,
         -0.08901668, -0.8320868 , -0.10182092, -0.67168915,  1.0480598 ,
         -0.38748235],
        [ 0.02496131, -0.14111662, -0.17897505, -0.00304999,  0.44673806,
          0.1360651 ,  0.40559214,  0.4466399 ,  0.17596686, -0.1268919