In [1]:
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/7c/3c/049400232ee2897d613db9009e42269417166c3f8519d46e5c97b6f9e206/tensorflow-2.15.0-cp310-cp310-win_amd64.whl.metadata
  Using cached tensorflow-2.15.0-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
  Obtaining dependency information for tensorflow-intel==2.15.0 from https://files.pythonhosted.org/packages/da/1b/63e20bde0db52c3be7e078b50cf507f4534ad6e47b5e2b01d9ed63bb652f/tensorflow_intel-2.15.0-cp310-cp310-win_amd64.whl.metadata
  Using cached tensorflow_intel-2.15.0-cp310-cp310-win_amd64.whl.metadata (5.1 kB)
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Obtaining dependency information for flatbuffers>=23.5.26


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Vocabulary size
voc_size = 500

In [6]:
# One hot representation
one_hot_repr = [one_hot(word, voc_size) for word in sent]
print(one_hot_repr)

[[154, 433, 423, 1], [154, 433, 423, 9], [154, 83, 423, 489], [26, 360, 168, 94, 19], [26, 360, 168, 94, 304], [241, 154, 182, 423, 179], [153, 435, 480, 94]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
# Pre Padding
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 154 433 423   1]
 [  0   0   0   0 154 433 423   9]
 [  0   0   0   0 154  83 423 489]
 [  0   0   0  26 360 168  94  19]
 [  0   0   0  26 360 168  94 304]
 [  0   0   0 241 154 182 423 179]
 [  0   0   0   0 153 435 480  94]]


In [9]:
# Feature Dimension
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
embedded_docs[0]

array([  0,   0,   0,   0, 154, 433, 423,   1])

In [12]:
embedded_docs[1]

array([  0,   0,   0,   0, 154, 433, 423,   9])

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 61ms/step


array([[ 0.03411711,  0.02516398,  0.02553746, -0.00817201,  0.01156045,
         0.02725771, -0.04881926,  0.02410932,  0.03943962, -0.03680196],
       [ 0.03411711,  0.02516398,  0.02553746, -0.00817201,  0.01156045,
         0.02725771, -0.04881926,  0.02410932,  0.03943962, -0.03680196],
       [ 0.03411711,  0.02516398,  0.02553746, -0.00817201,  0.01156045,
         0.02725771, -0.04881926,  0.02410932,  0.03943962, -0.03680196],
       [ 0.03411711,  0.02516398,  0.02553746, -0.00817201,  0.01156045,
         0.02725771, -0.04881926,  0.02410932,  0.03943962, -0.03680196],
       [ 0.03386265,  0.03911557,  0.02383659,  0.0159549 , -0.04910599,
         0.02696228,  0.04991797,  0.04749321, -0.03824332, -0.04521786],
       [-0.02601876, -0.02370684,  0.03008101, -0.04917151,  0.01495221,
        -0.00361984,  0.03019286, -0.0432439 , -0.01452588, -0.00098098],
       [ 0.00913091,  0.03162403, -0.03731697, -0.02104822, -0.0236153 ,
         0.00374798,  0.00593878,  0.03705964

In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 36ms/step


array([[[ 3.41171138e-02,  2.51639821e-02,  2.55374573e-02,
         -8.17201287e-03,  1.15604512e-02,  2.72577144e-02,
         -4.88192551e-02,  2.41093151e-02,  3.94396223e-02,
         -3.68019566e-02],
        [ 3.41171138e-02,  2.51639821e-02,  2.55374573e-02,
         -8.17201287e-03,  1.15604512e-02,  2.72577144e-02,
         -4.88192551e-02,  2.41093151e-02,  3.94396223e-02,
         -3.68019566e-02],
        [ 3.41171138e-02,  2.51639821e-02,  2.55374573e-02,
         -8.17201287e-03,  1.15604512e-02,  2.72577144e-02,
         -4.88192551e-02,  2.41093151e-02,  3.94396223e-02,
         -3.68019566e-02],
        [ 3.41171138e-02,  2.51639821e-02,  2.55374573e-02,
         -8.17201287e-03,  1.15604512e-02,  2.72577144e-02,
         -4.88192551e-02,  2.41093151e-02,  3.94396223e-02,
         -3.68019566e-02],
        [ 3.38626541e-02,  3.91155742e-02,  2.38365866e-02,
          1.59549005e-02, -4.91059907e-02,  2.69622840e-02,
          4.99179699e-02,  4.74932082e-02, -3.824331